# native

#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
#  profiles:
#     active: native
#  application:
#    name: config-server

server:
  port: 8002
# remote git
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fanhq/sprincloud-config-repo.git
          searchPaths: config-repo
          username: 944080287@qq.com
          password: Sbb2008@
      label: master
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/

management:
  security:
    enabled: false


